### CREATE
POST http://localhost:3049/api/urls/
Accept: 'application/json'
Content-Type: 'application/json'
{
"longUrl": "https://www.youtube.com/watch?v=oBQ-rhbzQJc",
"userId": 1
}

### GET
GET http://localhost:3049/api/urls/asd